# Theme
remote_theme: epidrome/cover-card@main

# Site Settings
title: 'Arun Vedachalam'
description: 'Chartered Accountant | Techie | Aquarist'

# Online profiles
Linkedin: 'www.linkedin.com/in/arunvedachalam/'
Telegram: 't.me/ArunVedachalam'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

social-links-order: [Linkedin,Telegram]

social-links:
  - name: Linkedin 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-linkedin

  - name: Telegram 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-instagram
