# Theme
remote_theme: epidrome/cover-card@main

# Site Settings
title: 'Arun Vedachalam'
description: 'Chartered Accountant | Techie | Aquarist'

# Online profiles
Linkedin: 'www.linkedin.com/in/arunvedachalam/'
Telegram: 't.me/ArunVedachalam'
Instagram: 'www.instagram.com/arun.vedachalam/'
Discord: 'discordapp.com/users/TheAll#4866'
Reddit: 'www.reddit.com/user/Arun_V7'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

social-links-order: [Linkedin,Instagram,Discord,Telegram,Reddit]

social-links:
  - name: Linkedin 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-linkedin

  - name: Telegram 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-telegram

  - name: Instagram 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-instagram
  
  - name: Discord 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-discord
    
    - name: Reddit 
    url-pattern: '__USERNAME__'
    url-scheme: 'https://'
    icon-class: fab fa-2x fa-reddit
    
